spring:

  datasource:
    url: ${PG_JDBC_URL:jdbc:postgresql://localhost:5432/checklist}
    username: ${PG_USRNAME:maxrunner}
    password: ${PG_PASSWORD:MetroidPrime2020}

  cache:
    caffeine.spec: expireAfterAccess=300s

logging:
  level:
    pt:
      credibom: ${APP_LOG_LEVEL:DEBUG}
    org:
      jooq:
        tools: ${LOG_LEVEL:DEBUG}
      springframework:
        security: ${LOG_LEVEL:DEBUG}
      arun: ${LOG_LEVEL:DEBUG}
    root: ${LOG_LEVEL:DEBUG}

