spring:

  datasource:
    url: ${PG_JDBC_URL:jdbc:postgresql://dsancalagon.linus.cbdomain.crb:8080/checklist_qua_credibom}
    username: ${PG_USRNAME:srv_qua_checklist_credibom}
    password: ${PG_PASSWORD:U3nbHvqHV27ojQWqt1vI}

  cache:
    caffeine.spec: expireAfterAccess=300s

logging:
  level:
    pt:
      credibom: ${APP_LOG_LEVEL:INFO}
    org:
      jooq:
        tools: ${LOG_LEVEL:INFO}
      springframework:
        security: ${LOG_LEVEL:INFO}
      arun: ${LOG_LEVEL:INFO}
    root: ${LOG_LEVEL:INFO}

