package pt.credibom.checklist.core.utils;

public interface PendingDocumentationConstants {

	final int ID_ESTADO_CONFORME = 1, ID_ESTADO_NAO_CONFORME = 2,ID_ESTADO_NAO_RECEBIDO = 3, ID_ESTADO_NAO_APLICAVEL = 4;

    final String ID_CATEGORIA_AUTO = "F";

    final int ID_PENDENTE_CONTRATO = 1, ID_PENDENTE_SEGURO = 2, ID_PENDENTE_SEPA = 3, ID_PENDENTE_DOCUMENTO_IDENTIFICACAO = 6;

    final String CODIGO_NIVEL3_DOCUMENTO_IDENTIFICACAO_1T = "CBM3", CODIGO_NIVEL3_DOCUMENTO_IDENTIFICACAO_2T = "CBM116";
}
